#!/usr/bin/env bash
set -e # Bail early
set -x # Very verbose

sudo apt-get update

sudo apt-get dist-upgrade

sudo apt-get -y install build-essential \
ssh \
vim \
tmux \
gradle \
gitweb \
htop \
glances \
tig \
ghc \
ncdu \
tree \
zsh \
silversearcher-ag \
pandoc \
valgrind \
ccache \
llvm \
clang \
multitail \
iotop \
cmake \
slurm \
coreutils \
autoconf \
automake \
m4

~/dotfiles/scripts/install.sh

~/dotfiles/append_my_bash_profile.sh

