#!/usr/bin/env bash
set -e # Bail early
set -x # Very verbose

GRADLE=gradle-2.4
GRADLE_FILE="${GRADLE}-bin.zip"
pushd /tmp
curl -sSL "https://services.gradle.org/distributions/${GRADLE_FILE}" -o /tmp/$GRADLE_FILE
unzip $GRADLE_FILE -d /usr/local/bin
ln -s /usr/local/bin/$GRADLE/bin/gradle /usr/local/bin/gradle
rm /tmp/$GRADLE_FILE
popd

