#!/usr/bin/env bash
set -e # Bail early
#set -x # Very verbose

VISUALVM=visualvm_138
VISUALVM_FILE=${VISUALVM}.zip

mkdir -p ~/bin
pushd ~/bin
curl -sSL "https://java.net/projects/visualvm/downloads/download/release138/${VISUALVM_FILE}" -o ~/bin/$VISUALVM_FILE
unzip $VISUALVM_FILE

rm $VISUALVM_FILE

ln -s ~/bin/${VISUALVM} ~/bin/visualvm
popd

