#!/usr/bin/env bash
set -e # Bail early
#set -x # Very verbose

GO=go1.4.2.linux-amd64
GOFILE=${GO}.tar.gz

mkdir -p ~/bin

(curl -sSL "https://storage.googleapis.com/golang/${GOFILE}" | tar -xz -C ~/bin)
