#!/usr/bin/env bash
set -e # Bail early
#set -x # Very verbose

VISUALVM=visualvm_138
VISUALVM_FILE=${VISUALVM}.zip

mkdir -p ~/bin
pushd ~/bin
curl -sSL "https://java.net/projects/visualvm/downloads/download/release138/${VISUALVM_FILE}" -o ~/bin/$VISUALVM_FILE
unzip $VISUALVM_FILE

rm $VISUALVM_FILE

ln -s ~/bin/${VISUALVM} ~/bin/visualvm

# Doesn't come with a good icon.  Grab one from the web.
curl -sSL "https://asset-1.java.net/attachments/images/project/visualvm.png?20150226.965aeb8" -o visualvm/etc/icon.png

popd

